from .main_handlers import *
from Main.backend.backend import *
from .profile import *
from .registration import *
from .contras import *
from .payment import *
from .admin_panel import *
from .question import *
from .withdraw import *
